kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
  labels:
    app: prometheus-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.10
    path: "/mnt/kubernetes/data/prometheus"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  selector:
    matchLabels:
      app: prometheus-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: prometheus-pv
